# Generated by Django 2.1.2 on 2018-11-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Clinic Manager'), (2, 'Warehouse Personnel'), (3, 'Dispatcher'), (4, 'Hospital Authority')], default=0),
            preserve_default=False,
        ),
    ]
