# Generated by Django 2.1.2 on 2018-10-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181030_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[(1, 'Loww'), (2, 'Medium'), (3, 'High')], default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Queued for Processingg'), (2, 'Processing by Warehouse'), (3, 'Queued for Dispatch'), (4, 'Dispatched'), (5, 'Delivered')], default=1, max_length=50),
        ),
    ]
