# Generated by Django 2.1.2 on 2018-10-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181030_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Queued for Processing'), (2, 'Processing by Warehouse'), (3, 'Queued for Dispatch'), (4, 'Dispatched'), (5, 'Delivered')], default=1),
        ),
    ]
