# Generated by Django 2.1.2 on 2018-10-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181030_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='altitude_meters',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=5, max_digits=9),
            preserve_default=False,
        ),
    ]
