# Generated by Django 2.1.3 on 2018-11-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181116_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
