# Generated by Django 2.1.2 on 2018-10-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181030_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='https://starkmans.com/pub/media/catalog/product/cache/image/1000x1320/e9c3970ab036de70892d86c6d221abfe/j/b/jb1324.jpg', upload_to='item_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='altitude_meters',
            field=models.PositiveIntegerField(),
        ),
    ]
