# Generated by Django 2.1.2 on 2018-10-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181030_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='altitude_meters',
            field=models.PositiveIntegerField(default=161),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=22.270257, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=114.131376, max_digits=9),
            preserve_default=False,
        ),
    ]
