# Generated by Django 2.1.2 on 2018-11-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181030_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_dispatched',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
